stages:
  - test

job_using_vault:
  stage: test
#  variables:
#    VAULT_AUTH_ROLE: gitlab-project-infra-iac-infrastructure
  id_tokens:
    VAULT_ID_TOKEN:
      aud: $VAULT_SERVER_URL
  secrets:
    TOKEN:
      vault: gitlab/projects/infra/iac/kubernetes/service_token/test@secret
  script:
    - echo $TOKEN
