stages:
  - test

job_using_vault:
  stage: test
#  variables:
#    VAULT_AUTH_ROLE: gitlab-project-infra-iac-infrastructure
  id_tokens:
    VAULT_ID_TOKEN:
      aud: $VAULT_SERVER_URL
  secrets:
    TOKEN:
      vault: infra/iac/kubernetes/test/password@gitlab-cicd
      file: false
  script:
    - echo $TOKEN
