- name: Deploy infrastructure
  hosts: localhost
  vars_files:
    - inventory/vars/awx.yaml
  roles:
    - role: infra.aap_configuration.controller_credential_types
      when: controller_credential_types is defined
      ignore_errors: true
    - role: infra.aap_configuration.controller_credentials
      when: controller_credentials is defined
    - role: infra.aap_configuration.controller_inventories
      when: controller_inventories is defined
    - role: infra.aap_configuration.controller_inventory_sources
      when: controller_inventory_sources is defined
    - role: infra.aap_configuration.controller_projects
      when: controller_projects is defined
    - role: infra.aap_configuration.controller_job_templates
      when: controller_templates is defined
