- name: Deploy freeipa infrastructure
  hosts: localhost
  vars_files:
    - inventory/vars/freeipa.yaml
  tasks:
    - name: Deploy nodes on proxmox
      ansible.builtin.include_role:
        name: proxmox_nodes
      vars:
        state: present

    - meta: refresh_inventory

  #  - name: Wait for each host to be joined in IPA
  #    ansible.builtin.include_role:
  #      name: wait_host_joined
  #    vars:
  #      joined_hosts: "{{ groups['pve_ipa'] | list }}" 

    - name: Short delay for final stages of join
      ansible.builtin.pause:
        seconds: 15

- name: Deploy freeipa replica
  hosts: freeipaservers
  become: true
  vars_files:
    - inventory/vars/freeipa.yaml
  tasks:
    - name: Set hostname 
      ansible.builtin.hostname: 
        name: '{{ ansible_hostname }}.{{ dns_zone }}'

    - name: Fix /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127.0.0.1 {{ ansible_hostname }}.{{ dns_zone }} {{ ansible_hostname }}$'
        line: '{{ ansible_default_ipv4.address }} {{ ansible_hostname }}.{{ dns_zone}} {{ ansible_hostname }}'

    - name: Fix /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^::1 {{ ansible_hostname }}.{{ dns_zone }} {{ ansible_hostname }}$'
        state: absent

    - debug:
        var: groups['freeipaservers'][0]
    - name: Add replicas to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}.{{ dns_zone }}"
        state: present
      when: item != ansible_hostname
      loop: "{{ groups['freeipaservers'] | list }}"

    - name: Disable IPv6
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: 1
        state: present
        reload: true
      loop: 
        - net.ipv6.conf.all.disable_ipv6
        - net.ipv6.conf.default.disable_ipv6
        - net.ipv6.conf.eth0.disable_ipv6

    - name: Setup IPA Replica
      ansible.builtin.include_role:
        name: freeipa.ansible_freeipa.ipareplica
      vars:
        state: present
