- name: Deploy K8S infrastructure
  hosts: localhost
  vars_files:
    - inventory/vars/sites/cbr/global.yaml
    - inventory/vars/sites/cbr/k8s.yaml
  tasks:
    - name: Deploy nodes on proxmox
      ansible.builtin.include_role:
        name: proxmox_nodes
      vars:
        state: present

    - name: Wait for each host to be joined in IPA
      ansible.builtin.include_role:
        name: wait_host_joined
      vars:
        joined_hosts: "{{ groups['pve_kube'] | list }}" 

    - name: Short delay for final stages of join
      ansible.builtin.pause:
        seconds: 5

    - meta: refresh_inventory

- name: Deploy K8S
  hosts: pve_kube
  become: true
  gather_facts: true
  vars_files:
    - inventory/vars/sites/cbr/global.yaml
    - inventory/vars/sites/cbr/k8s.yaml
  tasks:
    - name: Disable firewalld
      ansible.builtin.systemd_service:
        name: firewalld
        enabled: false
        state: stopped
        masked: true

    - name: Install node requirements
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - iscsi-initiator-utils
        - cryptsetup

    - name: Start and enable services
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - iscsid

    - name: Enable dm_crypt kernel module
      community.general.modprobe:
        name: dm_crypt
        state: present
        persistent: present

    - name: Deploy RKE2
      ansible.builtin.include_role:
        name: lablabs.rke2

    - name: Bootstrap Flux
      ansible.builtin.include_role:
        name: flux_bootstrap

