- name: Deploy Backup infrastructure
  hosts: localhost
  vars_files:
    - inventory/vars/backup-server.yaml
  tasks:
    - name: Deploy nodes on proxmox
      ansible.builtin.include_role:
        name: proxmox_nodes
      vars:
        state: present

    - meta: refresh_inventory

    - name: Wait for each host to be joined in IPA
      ansible.builtin.include_role:
        name: wait_host_joined
      vars:
        joined_hosts: "{{ groups['pve_backup'] | list }}" 

    - name: Short delay for final stages of join
      ansible.builtin.pause:
        seconds: 5

- name: Deploy Backup Server
  hosts: pve_backup
  become: true
  gather_facts: true
  vars_files:
    - inventory/vars/backup-server.yaml
  tasks:
    - name: Install prequisite packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: 
        - cifs-utils
        - restic
        
    - name: Create mount directories
      ansible.builtin.file:
        state: directory
        path: "{{ backup_src_dir }}/{{ item.name }}"
      loop: "{{ backup_paths }}"

    - name: Mount SMB shares
      ansible.posix.mount:
        src: "{{ smb_source }}/{{ item.name }}"
        path: "{{ backup_src_dir }}/{{ item.name }}"
        fstype: "cifs"
        opts: "{{ smb_opts }}"
        state: mounted
      loop: "{{ backup_paths }}"
      #"{{ query('subelements', backup_paths, 'sub_paths', {'skip_missing': True}) }}"
    
    - name: Create restic_folders variable
      ansible.builtin.set_fact:
        restic_folders: "{{ restic_folders|default([]) + [tmp] }}"
      vars:
        tmp: 
          path: "{{backup_src_dir}}/{{item.0.name}}/{{item.1}}"
      loop: "{{ query('subelements', backup_paths, 'sub_paths', {'skip_missing': True}) }}"

    - debug:
        var: restic_folders

    - name: Run restic role
      ansible.builtin.include_role:
        name: ansible-restic
