ansible_user: svc-ansible-infra
ansible_ssh_pass: "{{ vault_ipa_service_accounts.svc_ansible_infra.password }}"
ansible_become_pass: "{{ vault_ipa_service_accounts.svc_ansible_infra.password }}"
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

vm:
  target_nodes: ["vm"] # List of nodes to deploy the masters to must match master count (max )
  template: fedora42
  count: 1
  primary_count: 1
  cpu: 4
  memory: 8196
  disk_size: 60 # Disk size for root drive of VM in GB
  storage_pool: "local-lvm"
  bridge: "infranet"
  tag: 0
  tags: "infra,ipajoined"
  dns_server: "10.210.0.10"
  search_domain: cbr.infra.ashman.world
  ssh_pub_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF6leLiXjd46rW2/bKTyFtEBXv8A47Ti0kd49CcexgLy asher@fedora
  network_gateway: "{{ network.infra_cbr.gateway }}"
  network_subnet: "{{ network.infra_cbr.subnet }}"
  network_mask: "{{ network.infra_cbr.mask }}"
  network_start_ip: "{{ network.infra_cbr.start_ip.k8s }}"
  description: "Kubernetes hosts deployed by terraform"
  additional_networks: []

site: cbr
service_name: kube
dns_zone: cbr.infra.ashman.world

flux_repo_namespace: "ashmantis1"
flux_repo_name: "kubernetes"
flux_repo_path: "kubernetes/clusters/kube-cbr"
github_kubernetes_pat: "{{ vault_github_kubernetes_pat }}"

external_secrets_password: "{{ vault_ipa_service_accounts.svc_cbrk8s_vault.password }}"

rke2_ha_mode: true
rke2_ha_mode_keepalived: false
rke2_ha_mode_kubevip: true
rke2_api_ip: 10.210.3.100
rke2_kubevip_cloud_provider_enable: false
rke2_kubevip_svc_enable: false
rke2_version: v1.32.3+rke2r1 
rke2_custom_manifests:
  - templates/rke2-cilium-config.yaml
  - templates/external-secrets.yaml
  #  - templates/cilium-l2-policy.yaml
  #  - templates/cilium-lb-pool.yaml
  #  - templates/cilium-host-access-policy.yaml
rke2_cni:
  - cilium

rke2_kube_apiserver_args:
 - --oidc-client-id=kubelogin
 - --oidc-groups-claim=groups
 - --oidc-issuer-url=https://auth.cbr.k8s.ashman.world
 - --oidc-username-claim=email
disable_kube_proxy: true
#k8s_node_label:
#  - node-access: minimum-access
rke2_selinux: false
rke2_disable:
  - rke2-metrics-server
  - rke2-ingress-nginx
rke2_cluster_group_name: pve_kube
rke2_servers_group_name: pve_kube_primary
rke2_agents_group_name: pve_kube_secondary
rke2_download_kubeconf: true
rke2_download_kubeconf_path: /home/asher/.kube
rke2_download_kubeconf_file_name: rke2-cbr-kubeconfig-tmp-admin.yaml

rke2_interface: eth0
bind_address: "{{ hostvars[inventory_hostname]['ansible_' + rke2_interface]['ipv4']['address'] }}"

rke2_server_options:
  - "node-ip: {{ bind_address }}"
  #rke2_agent_options:
  #  - "node-ip: {{ rke2_bind_address }}"

