apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    app: external-secrets
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-secret
  namespace: external-secrets
stringData:
  password: {{ vault_ipa_service_accounts.svc_cbrk8s_vault.password }}
