apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    app: external-secrets
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-secret
  namespace: external-secrets
stringData:
  password: {{ external_secrets_password }}
