aap_hostname: "https://ansible.apps.ashman.world"
aap_username: svc-ansible-awx
aap_password: "{{ vault_ipa_service_accounts.svc_ansible_awx.password }}"
aap_validate_certs: true
organization: ashman

aap_configuration_async_retries: 200
controller_projects:
  - name: Infrastructure
    organization: "{{ organization }}"
    scm_type: git
    scm_url: "https://gitlab.apps.ashman.world/infra/iac/infrastructure.git"
    scm_update_on_launch: true
    credential: gitlab-infra
  - name: Inventories
    organization: "{{ organization }}"
    scm_type: git
    scm_url: "https://gitlab.apps.ashman.world/infra/ansible-inventory.git"
    scm_update_on_launch: false
controller_inventories:
  - name: proxmox_hosts
    description: Hosts sourced from proxmox
    organization: "{{ organization }}"
controller_inventory_sources:
  - name: proxmox-dynamic
    inventory: proxmox_hosts
    description: Proxmox dynamic inventory file
    credential: proxmox
    source: scm
    source_path: "awx.proxmox.yml"
    source_project: Inventories
    update_on_launch: true
controller_credential_types:
  - name: Proxmox-API-Token
    description: API Token for proxmox
    inputs:
      fields:
      - id: token
        type: string
        label: token
        secret: true
      required:
        - token
    injectors:
      env:
        PROXMOX_TOKEN_SECRET: !unsafe "{{ token }}"
controller_credentials:
  - name: proxmox
    description: Proxmox API token credentials
    organization: "{{ organization }}"
    credential_type: Proxmox-API-Token
    inputs:
      token: "{{ vault_awx.credentials.proxmox_api_token }}"
  - name: gitlab-infra
    credential_type: Source Control
    organization: "{{ organization }}"
    inputs:
      username: "awx"
      password: "{{ vault_awx.credentials.gitlab_infra.password }}"
  - name: ansible-infra
    credential_type: Machine
    organization: "{{ organization }}"
    inputs:
      username: "svc-ansible-infra"
      password: "{{ vault_ipa_service_accounts.svc_ansible_infra.password }}"
controller_templates:
  - name: "Update IPA Joined Hosts"
    job_type: run
    inventory: proxmox_hosts
    project: Infrastructure
    instance_groups:
      - infranet
    credentials:
      - infra-ansible-vault
      - ansible-infra
    playbook: update_hosts.yaml
  - name: "Update Vault version"
    job_type: run
    inventory: proxmox_hosts
    project: Infrastructure
    instance_groups:
      - infranet
    credentials:
      - infra-ansible-vault
      - ansible-infra
    playbook: update_vault.yaml
controller_schedules:
  - name: "Weekly Host Update - IPA Joined" 
    description: "Update IPA Joined hosts weekly" 
    unified_job_template: "Update IPA Joined Hosts"
    rrule: "DTSTART:20250101T023000Z RRULE:FREQ=WEEKLY;BYDAY=SU;INTERVAL=1"
  - name: "Weekly Vault Update" 
    description: "Keep Hashicorp Vault up to date" 
    unified_job_template: "Update Vault version"
    rrule: "DTSTART:20250101T043000Z RRULE:FREQ=WEEKLY;BYDAY=SU;INTERVAL=1"
